Introduce logging - Part 1 - Basic, globally configurable logging
open-component-model/ocm pull request #104
Opened 2022-09-08 08:49 UTC by Skarlso

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Relates to https://github.com/gardener/ocm/issues/64

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2022-09-08 10:57 UTC, yitsushi submitted a review, later dismissed
I don't think that's the right way long term, but for now it's still better as it allows to silence stdout.

Long term we should introduce some localized logging that can be configured. Logrus is a good choice and I love that, but with this approach all logging depends on global configuration and not local. The logical and elegant way would be to add a logger option to the context.

2022-09-14 08:12 UTC, yitsushi submitted a review, later dismissed

2022-09-16 13:33 UTC, jschicktanz requested changes
just some little things :)

2022-09-16 14:31 UTC, jschicktanz approved these changes

2022-09-19 10:06 UTC, yitsushi approved these changes

2022-09-19 10:15 UTC, merged