Toifixes
open-component-model/ocm pull request #304
Opened 2023-03-15 08:03 UTC by jensh007

**What this PR does / why we need it**:

*    Better documentation for examples in components/
*   fix packagespec in helmdemo

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release Notes**:

```feature user

```

2023-03-15 09:09 UTC, mandelsoft requested changes

2023-03-15 09:09 UTC, mandelsoft commented on components/helmdemo/packagespec.yaml
> +  additionalProperties: true
Maybe you should adjust the scheme to directly reflect the possible structure to get validation errors in case of using unsupported fields or typos.

2023-03-15 09:09 UTC, mandelsoft commented on components/helminstaller/Makefile
> -VERSION                                        := $(shell git describe --tags --exact-match 2>/dev/null|| echo "$$(cat $(REPO_ROOT)/VERSION)")
see above

2023-03-15 09:09 UTC, mandelsoft commented on components/helminstaller/README.md
> +# Usage
Maybe we shoud a ink to the cmds/hemlinstaller README. Here the config is explaines. (some docu added with the toi branch in mandelsoft). Should be merge it? (https://github.com/open-component-model/ocm/pull/305)

2023-03-15 13:09 UTC, jensh007 commented on components/helmdemo/Makefile
> -VERSION                                        = $(shell git describe --tags --exact-match 2>/dev/null|| echo "$$(cat $(REPO_ROOT)/VERSION)")
We do not have VERSION file anymore. Therefore change.
currently we get: 
```
git describe --tags
v0.3.0-rc.1-3-g3aa83cb8
```
This is inconvenient.
```
git describe --tags --exact-match 
fatal: no tag exactly matches '3aa83cb8b456d1c6eb3bfd25d6645219bc6c1aca'
``` 
does not work.

Any better suggestion is welcome.

2023-03-31 09:02 UTC, mandelsoft submitted a review, later dismissed

2023-04-04 12:39 UTC, mandelsoft approved these changes

2023-04-04 12:42 UTC, merged

2026-06-08 11:04 UTC, jakobmoellerdev commented
Still relevant in OCM v2. Root cert configuration via `rootcerts.config.ocm.software` in the config file needs to work correctly. The new `bindings/go/http` module was just added to v2 — this bug is now even more relevant as TLS/cert config is being consolidated there.

**Maps to v2 issues:** open-component-model/ocm-project#976 (TLS — Custom CA Certificates), open-component-model/ocm-project#978 (TLS — Client Certificate / mTLS).