generic object validation
open-component-model/ocm pull request #370
Opened 2023-05-22 13:23 UTC by mandelsoft

**What this PR does / why we need it**:

Add a `StrictMode`for the library to improve the object deserialization 
to validated the decoded objects against the initial data to check for
unexpected fields.

Add support to parse a set of object parts separately.

Fix all the the places where an object unmarshalling is delegated to 
unmarshal enriched object types using embedded fields. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release Notes**:

```feature user

```

2023-05-25 14:52 UTC, fabianburth approved these changes

2023-05-25 15:03 UTC, fabianburth requested changes

2023-05-25 15:03 UTC, fabianburth commented on pkg/runtime/validation/validate.go
Add a short documentation to each function

2023-05-26 12:36 UTC, fabianburth approved these changes

2023-07-05 08:34 UTC, merged

2023-07-06 06:11 UTC, jensh007 commented
Seems to break integration tests: https://github.com/open-component-model/ocm-integrationtest/actions/runs/5470925337/jobs/9961537438