Component archive
open-component-model/ocm pull request #399
Opened 2023-06-29 16:34 UTC by fabianburth

**What this PR does / why we need it**:
The possibility to have Component Archives with with uncompressed/unpacked resources in a directory enables more convenient test cases. This is especially useful as it allows the ocm-lib to deal with the already existing test cases in the gardener landscaper. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release Notes**:

```feature user

```

2023-06-29 18:22 UTC, mandelsoft requested changes

2023-06-29 18:22 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/comparch/accessmethod_localfs.go
> +	return m.blobAccess.Close()
You have to check for nil, first.

And you should introduce a `sync.Mutex` here, to protect the handling of the cached access.

2023-06-29 18:22 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/comparch/accessmethod_localfs.go
> +	return accessio.BlobData(m.blobAccess, nil)
yes, the original code never closed the data access. This is definitely  the right way to deal with this.: cache the access until the method is closed.

2023-06-29 18:22 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/comparch/comparch_test.go
> +		defer acc.Close()
you should use the `defer Close(acc)`-like way supported by the testutils. It checks for the err code, also.

2023-06-29 18:22 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/comparch/comparch_test.go
> +		repo := Must(spec.Repository(octx, nil))
Close the repo (see below)

2023-06-29 18:22 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/comparch/comparch_test.go
> +		cv := Must(repo.LookupComponentVersion("example.com/root", "1.0.0"))
Close the cv (see below)

2023-06-29 18:22 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/comparch/comparch_test.go
> +	It("component archive with resource stored as tar", func() {
see comments for test below

2023-06-29 18:22 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/comparch/testdata/directory/blobs/root/blueprint.yaml
> +# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
may be you should just use some data here, and not a real blueprint.

2023-06-29 18:54 UTC, fabianburth commented on pkg/contexts/ocm/plugin/plugin_test.go
> -	"github.com/open-component-model/ocm/pkg/contexts/ocm/cpi"
Yes, but conveniently running `make prepare` (or `make format`) before pushing without affecting files other than the ones edited in the specific PR would require everyone to this each time before merging their PR.

2023-06-29 19:42 UTC, fabianburth commented on pkg/common/accessio/opts.go
> +	FileFormat *FileFormat `json:"fileFormat,omitempty"`
If the file format is not set, the format is automatically detected during the `spec.Repository()`call.

2023-06-30 08:24 UTC, fabianburth commented on docs/pluginreference/plugin_accessmethod.md
> +* [plugin accessmethod <b>identity</b>](plugin_accessmethod_identity.md)	 &mdash; get blob identity
It appears so (was generated during `make prepare` - we should probably make it a habit running it for every PR).

2023-07-13 08:39 UTC, mandelsoft approved these changes

2023-07-13 09:44 UTC, mandelsoft approved these changes

2023-07-13 09:44 UTC, merged