Gardener config credential repository
open-component-model/ocm pull request #55
Opened 2022-08-11 13:10 UTC by jschicktanz

**What this PR does / why we need it**:
Add Gardener config credential repository which can read credentials in a data format used by the Gardener Pipelines (see https://github.com/gardener/cc-utils/tree/master/model). Credentials can be handed to the client either via local files or a http server (see https://github.com/gardener/cc-utils/blob/master/ccc/secrets_server.py#L29).

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/ocm/issues/34

**Special notes for your reviewer**:

**Release note**:

```feature user
- Add Gardener config credential repository
```

2022-08-15 10:51 UTC, Skarlso reviewed
This looks pretty okay to me as far as I understand it. I leave the final approve to @mandelsoft  :)

2022-08-16 13:52 UTC, mandelsoft requested changes

2022-08-19 10:53 UTC, mandelsoft submitted a review, later dismissed

2022-08-26 10:07 UTC, Skarlso submitted a review, later dismissed

2022-08-30 15:50 UTC, mandelsoft requested changes

2022-09-02 12:55 UTC, mandelsoft approved these changes

2022-09-02 13:39 UTC, Skarlso approved these changes

2022-09-02 13:40 UTC, merged