Embedded spec for the OCM model elements and their relations to each other
open-component-model/ocm pull request #58
Opened 2022-08-13 10:38 UTC by mandelsoft

**What this PR does / why we need it**:

This is work in progress.
I do not find this draft button on the github UI

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2022-08-15 08:22 UTC, Skarlso requested changes
Half-way through. :)

2022-08-15 10:37 UTC, Skarlso requested changes
Some additional review notes.

2022-08-16 09:25 UTC, Skarlso approved these changes
Thanks LGTM!

2022-08-22 08:44 UTC, jschicktanz approved these changes

2022-08-24 06:44 UTC, merged