Refactor of the code base: Remove underscore functions and refactor a panic
open-component-model/ocm pull request #59
Opened 2022-08-16 15:22 UTC by Skarlso

**What this PR does / why we need it**:

Cleanup and replacing panics and error handling.

This is branched off from #57. I'll rebase once that's merged.

**Which issue(s) this PR fixes**:
Related to #52. This doesn't close it yet.

I also removed the `test` package. It shouldn't be living with the codebase.

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2022-08-19 11:48 UTC, yitsushi reviewed
`AddKnownTypes()` is in the repo, but in a different package, so technically it's en external call.

2022-08-19 13:09 UTC, yitsushi approved these changes

2022-08-24 14:31 UTC, mandelsoft requested changes

2022-08-29 13:08 UTC, mandelsoft approved these changes

2022-08-29 13:09 UTC, merged