Npm/config
open-component-model/ocm pull request #653
Opened 2024-02-13 14:48 UTC by hilmarf

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [x] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue #633

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-15 13:32 UTC, mandelsoft requested changes

2024-02-16 07:57 UTC, hilmarf commented on pkg/contexts/credentials/repositories/npm/provider.go
> +		}
correct, but where do I get it from?

2024-02-16 07:57 UTC, hilmarf commented on pkg/contexts/credentials/repositories/npm/config.go
> +	for _, e := range prop {
obsolete... useless leftover from copy&paste - will delete

2024-02-16 08:03 UTC, hilmarf commented on pkg/contexts/credentials/repositories/npm/repository.go
> +	r.ctx.RegisterConsumerProvider(id, &ConsumerProvider{path})
but I want this to always register...

2024-02-16 13:55 UTC, mandelsoft commented on pkg/contexts/credentials/repositories/npm/repository.go
> +	r.ctx.RegisterConsumerProvider(id, &ConsumerProvider{path})
It should be a consistent behaviour for all externsions.

2024-02-22 09:18 UTC, mandelsoft approved these changes

2024-02-22 09:18 UTC, merged