enable http registries as ocm repositories
open-component-model/ocm pull request #676
Opened 2024-02-29 15:46 UTC by fabianburth

## Description
So far, it was not possible to use a `http` OCI registry as OCM repository, thus, `https` was required (primarily due to parsing). Preparing the certificates and passing them to the corresponding places can be quite cumbersome for test scenarios. 

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Screenshots

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-18 09:38 UTC, hilmarf approved these changes
LGTM

2024-03-19 14:04 UTC, mandelsoft requested changes

2024-03-19 14:04 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/comparch/uniform.go
> -
Because this was al alternate for the ref parsing, there was no registered ShortType.

2024-03-19 14:04 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/ctf/type.go
> +)
same here

2024-03-19 14:04 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/genericocireg/type.go
> +	ShortType = ocireg.ShortType
same here

2024-03-19 14:04 UTC, mandelsoft commented on pkg/contexts/ocm/repositories/ocireg/type.go
same here

2024-03-19 16:12 UTC, Skarlso commented
I'm honestly a bit against this. There is a reason for not supporting insecure repositories. ocm-controller is using self-signed certificates to set up testing registries that use HTTPS. It's super easy to create a secure registry for testing.

In the wild you should never EVER use an insecure HTTP registry. So I don't see the point of this change.

2024-03-21 09:22 UTC, fabianburth commented
I'm open for discussion. Currently, you will at least get a warning if you use http and if you do not specify a scheme, it will default to https.
But on one hand, there are several people that just want to start a registry locally and fool around a bit to get to know ocm's functionality. On the other hand, I'm not sure whether it really is that easy for all application using ocm to get your application trust the self-signed certificate.

2024-03-21 09:24 UTC, Skarlso commented
@fabianburth you're right, the lower the entry for getting started the better the adoption. :)

2024-03-21 09:25 UTC, Skarlso commented
>On the other hand, I'm not sure whether it really is that easy for all application using ocm to get your application trust the self-signed certificate.

You can use mkcert to generate a self-signed, trusted cert, than when you are launching the registry, just pass the cert in as an environment property and everything should work. :)

2024-03-21 10:00 UTC, fabianburth commented
So, I'm not strictly talking about command line usage here. Let's consider integration tests and say you start your application and also your registry in cluster. Now, it might already be kind of a hassle to get your application to trust the certificate, mightn't it?

2024-03-21 19:43 UTC, Skarlso commented
>Now, it might already be kind of a hassle to get your application to trust the certificate, mightn't it?

Not really, no. In fact, we use an HTTPS registry in our e2e tests here: 

https://github.com/open-component-model/ocm-controller/tree/main/e2e

You'll see that we deploy cert-manager, generate a certificate, download it, install in the local store using mkcert, and done. Everything is running with HTTPS.

This is all we needed to do to get things running https://github.com/open-component-model/ocm-controller/blob/main/hack/prime_test_cluster.sh.

We only test using HTTPS.

2024-04-23 12:17 UTC, mandelsoft approved these changes

2024-04-23 12:34 UTC, merged