cli: verify digests
open-component-model/ocm pull request #681
Opened 2024-03-04 16:50 UTC by mandelsoft

## Description

Enable the cli command `verify component` to verify digests without signature validation

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Screenshots

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-05 07:07 UTC, hilmarf requested changes
LGTM, but there are some test failures:
https://github.com/open-component-model/ocm/actions/runs/8144045884/job/22257282304?pr=681

2024-03-05 16:40 UTC, fabianburth approved these changes

2024-03-05 16:41 UTC, fabianburth requested changes
unit tests still failing

2024-03-05 17:05 UTC, fabianburth approved these changes

2024-03-06 07:26 UTC, hilmarf commented on cmds/ocm/commands/ocmcmds/common/cmds/signing/cmd.go
> +		if len(sopts.SignatureNames) > 0 || sopts.Issuer != nil || sopts.Keyless {
What's the meaning of `Keyless`? It looks odd: "if there is no key (aka. Keyless), then verify the signature" ... I don't get it

2024-03-06 07:27 UTC, hilmarf approved these changes

2024-03-06 08:28 UTC, merged