OCM localization support
open-component-model/ocm pull request #70
Opened 2022-08-28 17:09 UTC by mandelsoft

**What this PR does / why we need it**:

This PR provides some support for localization and configuration of filesystem snapshots
based on information provided by component versions and user configuration.

Additionally, it contains a fix for the Tar resource generation.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2022-09-02 11:17 UTC, Skarlso requested changes
Some change requests in comments above.

2022-09-05 11:47 UTC, Skarlso submitted a review, later dismissed

2022-09-06 15:20 UTC, Skarlso submitted a review, later dismissed

2022-09-06 15:59 UTC, Skarlso submitted a review, later dismissed

2022-09-07 07:57 UTC, yitsushi submitted a review, later dismissed

2022-09-07 16:05 UTC, Skarlso approved these changes

2022-09-08 10:42 UTC, yitsushi approved these changes

2022-09-08 12:52 UTC, merged