Fix cache
open-component-model/ocm pull request #705
Opened 2024-03-18 16:40 UTC by fabianburth

## Description
The repository cache was not able to deal with repository specs that contained fields that cannot be marshalled (since the marshalled repository spec is used as key). 

This issue was already resolved in the session implementation that essentially implemented its own repository cache. To reduce code duplication and avoid such errors in the future, the session now uses the repository cache implementation. 

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Related Issue # (issue)
- Closes # (issue)
- Fixes # (issue)
> Remove if not applicable

## Screenshots

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-19 10:00 UTC, hilmarf submitted a review, later dismissed
can't really judge on this... but looks okish

2024-03-21 15:50 UTC, mandelsoft requested changes

2024-03-21 15:50 UTC, mandelsoft commented on pkg/contexts/ocm/session.go
> +		}
check before caching the repo

2024-03-21 16:06 UTC, mandelsoft approved these changes

2024-03-21 16:14 UTC, merged