rework selectors
open-component-model/ocm pull request #858
Opened 2024-07-30 11:57 UTC by mandelsoft

#### What this PR does / why we need it:

A new ocm sub package `selectors` now bundles an enhanced mechanism to select 
resources, sources and references for a component descriptor as well as for a component version.
The old methods there are deprecated.

Particular sub packaged (rscsel, srcsel, refsel) provide a type specific view for common and special selector functions and the appropriate logical operators And,Or and Not.

2024-07-30 15:22 UTC, fabianburth requested changes

2024-07-30 15:24 UTC, mandelsoft commented on pkg/contexts/ocm/compdesc/helper.go
> +func (cd *ComponentDescriptor) GetResources(sel ...rscsel.Selector) []Resource {
THis method already existed earlier and should be kept. I just added the new Select methods.

2024-07-30 15:25 UTC, mandelsoft commented on pkg/contexts/ocm/compdesc/helper.go
> +func (cd *ComponentDescriptor) GetReferences(sel ...refsel.Selector) []ComponentReference {
see GetResources

2024-07-30 15:25 UTC, mandelsoft commented on pkg/contexts/ocm/cpi/dummy.go
> +func (d *DummyComponentVersionAccess) GetResources(sel ...rscsel.Selector) []ResourceAccess {
see GetResources

2024-07-30 15:25 UTC, mandelsoft commented on pkg/contexts/ocm/cpi/dummy.go
> +func (d *DummyComponentVersionAccess) GetSources(sel ...srcsel.Selector) []SourceAccess {
see GetResources

2024-07-30 15:27 UTC, mandelsoft commented on pkg/contexts/ocm/selectors/identity.go
> +func NewAIdentityErrorSelectorImpl(s IdentitySelector, err error) *IdentityErrorSelectorImpl {
fixed

2024-07-31 06:57 UTC, fabianburth requested changes

2024-07-31 06:57 UTC, fabianburth commented on pkg/contexts/ocm/selectors/label.go
> +func GetLabels(labels v1.Labels, sel ...LabelSelector) []v1.Label {
```suggestion
func SelectLabelsSilent(labels v1.Labels, sel ...LabelSelector) []v1.Label {
```

2024-07-31 09:28 UTC, fabianburth approved these changes

2024-07-31 09:32 UTC, merged