fix closure + digest mode + ctf index
open-component-model/ocm pull request #973
Opened 2024-10-17 11:48 UTC by mandelsoft

#### What this PR does / why we need it

- Calling `ocm hash components -U` provides hashes as top-level state, and not on the level of component references.
The reason is , that the digest mode is not initialized in the signing options.

- The index of the OCI ctf does not handle tag updates correctly. It does not remove the old digest to tag mapping.

- The Recursion modes of the CI does not work correctly for closable elements. The Exploder had no access to the session hasn't added the injected new elements to the session. Therefore the repository could not be closed, which left the index state unchanged on the filesystem. The error from the deferred close was ignores .

#### Which issue(s) this PR fixes

2024-10-17 13:34 UTC, fabianburth requested changes

2024-10-17 16:33 UTC, mandelsoft commented on api/oci/extensions/repositories/ctf/index/index.go
> +				}
A digest may be found in multiple repositories, but we are working on a dedicated one, only.

2024-10-17 16:34 UTC, mandelsoft commented on api/oci/extensions/repositories/ctf/index/index.go
> +				}
BTW: what is the different in your suggested change?

2024-10-18 07:28 UTC, fabianburth commented on api/oci/extensions/repositories/ctf/index/index.go
> +				}
ah, you are correct.

2024-10-18 07:44 UTC, fabianburth approved these changes

2024-10-18 08:05 UTC, merged