Introduce update state on CV implementation API
open-component-model/ocm pull request #976
Opened 2024-10-17 18:26 UTC by mandelsoft

#### What this PR does / why we need it

Extend the CV implementation API to provide information, whether an Update of the descriptor has been done.
This information is then used to trigger the pubsub handler.
If no update has been done, the query of the repository's pubsub info is omitted.

#### Which issue(s) this PR fixes

2024-10-18 08:25 UTC, fabianburth requested changes

2024-10-18 08:25 UTC, fabianburth commented on api/ocm/extensions/repositories/composition/repository.go
> +		return true, accessio.ErrReadOnly
Why do we return `true` here?

2024-10-18 08:25 UTC, fabianburth commented on api/ocm/extensions/repositories/virtual/example/example.go
> +			return true, accessio.ErrReadOnly
same thing here?

2024-10-18 08:26 UTC, fabianburth commented
are there tests for this behaviour?

2024-10-18 14:34 UTC, mandelsoft commented on api/ocm/extensions/repositories/composition/repository.go
> +		return true, accessio.ErrReadOnly
fixed for all such returns

2024-10-21 06:44 UTC, frewilhelm commented
Will this fix https://github.com/open-component-model/ocm/issues/872?

2024-10-21 09:25 UTC, jakobmoellerdev commented
just needs a rebase and a rereview

2024-10-21 11:13 UTC, jakobmoellerdev approved these changes
LGTM

2024-10-21 11:38 UTC, jakobmoellerdev commented
> Will this fix #872?

no @frewilhelm

2024-10-21 11:39 UTC, hilmarf approved these changes

2024-10-21 11:49 UTC, merged